In [2]:
import numpy as np

real_part = np.array([1, 2, 3])
imag_part = np.array([4, 5, 6])
magnitude = np.array([7, 8, 9])
# These arrays could represent data from three different signals. Each array is just a list of numbers.



features = np.column_stack([real_part, imag_part, magnitude])
print(features)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
simple_clone_dataset = {
    'cirs': np.array(
        [
            [ # CIR 1
                [ # Alice - channel
                    [1, 2],
                    [3, 4],
                    [5, 6] # .... [251]
                ],
                [ # other channel
                    [9, 10],
                    [11, 12],
                    [13, 14]
                ],
                [ # other channel
                    [170, 180],
                    [190, 200],
                    [210, 220]
                ]
            ],
            [ # CIR 2
                [ # Alice
                    [25, 26],
                    [27, 28],
                    [29, 30]
                ],
                [
                    [33, 34],
                    [35, 36],
                    [37, 38]
                ],
                [
                    [410, 420],
                    [430, 440],
                    [450, 460]
                ]
            ],
            [ # CIR 3
                [
                    [49, 50],
                    [51, 52],
                    [53, 54]
                ],
                [
                    [57, 58],
                    [59, 60],
                    [61, 62]
                ],
                [
                    [650, 660],
                    [670, 680],
                    [690, 700]
                ]
            ]
        ]
    )
}
print(simple_clone_dataset['cirs'])

In [22]:
real_part = simple_clone_dataset['cirs'][:3, 2, :, 0]
imag_part = simple_clone_dataset['cirs'][:3, 2, :, 1]
magnitude = np.abs(real_part + 1j * imag_part)
print('Real')
print(real_part)
print('Imag')
print(imag_part)
print('Magnitude')
print(magnitude)
print()


# These arrays could represent data from three different signals. Each array is just a list of numbers.
print('Column stack')
features = np.column_stack([real_part, imag_part, magnitude])
print(features)
print(features.shape)

print('-----------------')
print('Stack')
features = np.stack([real_part, imag_part, magnitude], axis=1)
print(features)
print(features.shape)

print('-----------------')
# num_samples, num_features, num_components = features.shape
# features_reshaped = features.reshape(-1, num_components)
# print(features_reshaped)

Real
[[170 190 210]
 [410 430 450]
 [650 670 690]]
Imag
[[180 200 220]
 [420 440 460]
 [660 680 700]]
Magnitude
[[247.58836806 275.86228448 304.13812651]
 [586.94122363 615.22353661 643.50602173]
 [926.33687177 954.62034338 982.90386102]]

Column stack
[[170.         190.         210.         180.         200.
  220.         247.58836806 275.86228448 304.13812651]
 [410.         430.         450.         420.         440.
  460.         586.94122363 615.22353661 643.50602173]
 [650.         670.         690.         660.         680.
  700.         926.33687177 954.62034338 982.90386102]]
(3, 9)
-----------------
Stack
[[[170.         190.         210.        ]
  [180.         200.         220.        ]
  [247.58836806 275.86228448 304.13812651]]

 [[410.         430.         450.        ]
  [420.         440.         460.        ]
  [586.94122363 615.22353661 643.50602173]]

 [[650.         670.         690.        ]
  [660.         680.         700.        ]
  [926.33687177 954.62034

In [5]:
#---------------- np.empty()---------------
# Create an empty array with shape (3, 2)
array = np.empty((3, 2))

print("Empty array:")
print(array)

Empty array:
[[6.91117021e-310 6.91117021e-310]
 [1.58101007e-322 1.58101007e-322]
 [3.84333666e-320 0.00000000e+000]]


In [21]:
# Interleave columns
interleaved = np.empty((real_part.shape[0], real_part.shape[1] * 3), dtype=float)
print(real_part.shape)
interleaved[:, 0::3] = real_part
print(real_part)
interleaved[:, 1::3] = imag_part
print(interleaved)
interleaved[:, 2::3] = magnitude
print(interleaved.reshape(1, -1))

(3, 3)
[[170 190 210]
 [410 430 450]
 [650 670 690]]
[[1.700e+002 1.800e+002 1.220e-321 1.900e+002 2.000e+002 1.359e-321
  2.100e+002 2.200e+002 1.502e-321]
 [4.100e+002 4.200e+002 2.895e-321 4.300e+002 4.400e+002 3.039e-321
  4.500e+002 4.600e+002 3.177e-321]
 [6.500e+002 6.600e+002 4.575e-321 6.700e+002 6.800e+002 4.713e-321
  6.900e+002 7.000e+002 4.852e-321]]
[[170.         180.         247.58836806 190.         200.
  275.86228448 210.         220.         304.13812651 410.
  420.         586.94122363 430.         440.         615.22353661
  450.         460.         643.50602173 650.         660.
  926.33687177 670.         680.         954.62034338 690.
  700.         982.90386102]]
