In [9]:
import numpy as np
import matplotlib.pyplot as plt

# Load measurement file:
measurement = np.load('dataset/meas_asymm_1.npz')
header, data = measurement['header'], measurement['data']

# print(header.dtype)
print(data.dtype)

[('timestamp', '<f8'), ('tag_position', '<f8', (3,)), ('speeds', [('forward', '<f8'), ('backward', '<f8'), ('rotation', '<f8')]), ('cirs', '<i2', (15, 251, 2)), ('rssis', '<f8', (15,))]


In [2]:
print('Header information:')
anchor_positions = header['anchor_positions']
sq_anchor_positions = anchor_positions.squeeze()

print('Anchor positions (coordinates in mm):')
for i, anchor in enumerate(sq_anchor_positions):
    print(f'A{i}: ({anchor[0]}, {anchor[1]}, {anchor[2]})')

Header information:
Anchor positions (coordinates in mm):
A0: (204.0, 2859.0, 1150.0)
A1: (5658.0, 2856.0, 1150.0)
A2: (2900.0, 184.0, 1150.0)


In [3]:
print('Channels:')
channels = header['channels'].squeeze()
# print(channels)
print('Trasmitter -> receiver, msg:')
for i, c in enumerate(channels):
    print(f'{c["transmitter"]} -> {c["receiver"]}, msg: #{c["index"]}')

Channels:
Trasmitter -> receiver, msg:
t0 -> a0, msg: #0
t0 -> a1, msg: #0
t0 -> a2, msg: #0
a0 -> t0, msg: #0
a0 -> a1, msg: #0
a0 -> a2, msg: #0
a1 -> t0, msg: #0
a1 -> a0, msg: #0
a1 -> a2, msg: #0
a2 -> t0, msg: #0
a2 -> a0, msg: #0
a2 -> a1, msg: #0
t0 -> a0, msg: #1
t0 -> a1, msg: #1
t0 -> a2, msg: #1


In [8]:
print('Average CIR cross-correlations:')
average_correlations = np.zeros((len(channels), len(channels)))
print(average_correlations)
# for i, j in itertools.combinations_with_replacement(range(len(channels)), 2):
    
    # print(f' ({i},{j})')
    # # Create array of correlations:
    # ccs = np.fromiter(
    #     (cir_correlation(row['cirs'][i], row['cirs'][j]) for row in data),
    #     dtype=numpy.float64, count=len(data))

    # # Calculate and print average:
    # average_correlations[i, j] = numpy.average(ccs)
    # average_correlations[j, i] = average_correlations[i, j]
    # print(f'  {i:2d} <-> {j:2d}: {average_correlations[i, j]:.2f}')

Average CIR cross-correlations:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
