In [12]:
import numpy as np

# Array slicing
data = {
    'cirs': np.array(
        [ # CIR (9797)
            [ # channel (15)
                [ #sample (251)
                    [1, 2], # real, imag 
                    [3, 4]
                ],
                [   
                    [5, 6], 
                    [7, 8]
                ]
            ],
            [
                [[9, 10], [11, 12]],
                [[13, 14], [15, 16]]
            ],
            [
                [[17, 18], [19, 20]],
                [[21, 22], [23, 24]]
            ]
        ]
    )
}
data_cir = data['cirs']

alice_real = data_cir[:, 0, :, 0]
alice_imag = data_cir[:, 0, :, 1]

alice_feature = np.column_stack((alice_real, alice_imag))
print(alice_feature)

print(np.hstack((alice_real, alice_imag)).flatten())

[[ 1  3  2  4]
 [ 9 11 10 12]
 [17 19 18 20]]
[ 1  3  2  4  9 11 10 12 17 19 18 20]
